//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magistral40
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Articles", Schema = "u7716449_vxod")]
    public partial class Articles
    {
       
        public int Id { get; set; }
        public string Context { get; set; }
        public string Header { get; set; }
        public string Description { get; set; }
        public string title { get; set; }
        public string keywords { get; set; }
        public string UrlDescriptImg { get; set; }
        public int Position { get; set; }
        public bool Visible { get; set; }
        public string Menu { get; set; }
        public string URL { get; set; }
        public string Layout { get; set; }
        public string Razdel { get; set; }
        public string SmallDescript { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
