//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magistral40
{
    using System;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Messager", Schema = "u7716449_vxod")]
    public partial class Messager
    {
        [Required]
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }


        [Display(Name = "Телефон")]
        public string Phone { get; set; }


        [Display(Name = "Как к Вам обращаться")]
        public string UserName { get; set; }


        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Неверный формат электронной почты")]
        [Display(Name = "Email")]
        public string EmailAdrress { get; set; }


        [StringLength(500)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Текст сообщения")]
        public string Message { get; set; }

        [Required]
        [DataType(DataType.DateTime)]
        public DateTime Date { get; set; }
    }
}
