//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magistral40
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    [Table("Prices", Schema = "u7716449_vxod")]
    public partial class Prices
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string IE { get; set; }
        public Nullable<float> Price { get; set; }
        public string Group_Name { get; set; }
        public string Group_Name_Main { get; set; }
        public string URL { get; set; }
        public Nullable<int> SortIndex { get; set; }
    }
}
